<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DataTest extends Model
{
    use HasFactory;
    protected $fillable = [
        'favorite_app_flag',
        'ecom_category',
        'search_type',
        'platform',
        'category',
        'tag_ids',
        'ad_positions',
        'ads_ai_category',
        'video_duration_type',
        'os',
        'ads_promote_type',
        'geo',
        'exclude_geo',
        'audience_sex',
        'audience_age',
        'game_play',
        'game_style',
        'type',
        'page',
        'industry',
        'language',
        'keyword',
        'sort_field',
        'region',
        'seen_begin',
        'seen_end',
        'original_flag',
        'is_preorder',
        'resume_or_new_ads',
        'is_real_person',
        'theme',
        'text_md5',
        'ads_size',
        'size',
        'ads_format',
        'exclude_keyword',
        'cod_flag',
        'is_theater',
        'is_ai_app',
        'landing_page',
        'cta_type',
        'new_ads_flag',
        'like_begin',
        'like_end',
        'comment_begin',
        'comment_end',
        'share_begin',
        'share_end',
        'position',
        'is_hide_advertiser',
        'advertiser_key',
        'dynamic',
        'shopping',
        'duplicate',
        'software_types',
        'ecom_types',
        'social_account',
        'modules',
        'page_id',
        'landing_type',
        'is_first',
        'page_load_more',
        'source_app',
        'redirect_filter_type',
    ];
    // protected $casts = [
    //     'favorite_app_flag' => 'boolean',
    //     'original_flag' => 'boolean',
    //     'is_preorder' => 'boolean',
    //     'is_real_person' => 'boolean',
    //     'is_theater' => 'boolean',
    //     'is_ai_app' => 'boolean',
    //     'new_ads_flag' => 'boolean',
    //     'is_hide_advertiser' => 'boolean',
    //     'dynamic' => 'boolean',
    //     'shopping' => 'boolean',
    //     'duplicate' => 'boolean',
    //     'is_first' => 'boolean',
    //     'seen_begin' => 'datetime',
    //     'seen_end' => 'datetime',
    //     'like_begin' => 'datetime',
    //     'like_end' => 'datetime',
    //     'comment_begin' => 'datetime',
    //     'comment_end' => 'datetime',
    //     'share_begin' => 'datetime',
    //     'share_end' => 'datetime',
    //     'tag_ids' => 'array',
    //     'ad_positions' => 'array',
    //     'software_types' => 'array',
    //     'ecom_types' => 'array',
    //     'modules' => 'array',
    // ];
}
